"$schema" = 'https://jj-vcs.github.io/jj/prerelease/config-schema.json'

[user]
name = "Scotte Zinn"
email = "scotte@zinn.ca"

[ui]
default-command = "log"
diff.format = "git"
editor = "nvim"
pager = ["delta", "--pager", "less -FRX"]

[merge-tools.delta]
diff-expected-exit-codes = [0, 1]

[git]
sign-on-push = false
subprocess = true

[aliases]
l = ["log", "-r", "ancestors(reachable(@, mutable()), 2)"]
la = ["log", "-r", "::@"]
nt = ["new", "trunk()"]
rebase-all = ["rebase", "-s", "all:roots(trunk()..mutable())", "-d", "trunk()"]

[signing]
backend = "ssh"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC2VWgq5MEINPHdTEx9jhDxXB80ZjWOXB9M0X0XtoHih"
