---
- name: "install chezmoi"
  community.general.homebrew:
    name:
      - chezmoi
  tags: homebrew

- name: "check for sops key"
  stat:
    path: '{{ xdg_config_home }}/sops/age/keys.txt'
  register: keys_txt

- name: "grab keys.txt from 1password"
  ansible.builtin.command: op document get "rjrmnx5rctflmpstxhagjq3hom"
  register: keys_txt_output
  when: not keys_txt.stat.exists  

- name: "install keys.txt"
  copy:
    content: "{{ keys_txt_output.stdout | replace('\\n', '\n') }}"
    dest: "{{ xdg_config_home }}/sops/age/keys.txt"
  when: not keys_txt.stat.exists

- name: "chezmoi init"
  ansible.builtin.command:
    cmd: chezmoi init --apply {{ dotfiles.repo }} --branch {{ dotfiles.branch }}
  args:
    creates: "{{ xdg_data_home }}/chezmoi"

- name: "chezmoi update"
  ansible.builtin.command: chezmoi update --force
  register: chezmoi_update
  changed_when: '"Updating" in chezmoi_update.stderr'
