---
- name: "install"
  community.general.homebrew:
    name:
      - 'fish'
  tags: homebrew

- block:
    - name: "obtain path to fish"
      ansible.builtin.command: which fish
      register: fish_path
      changed_when: false

    - name: add homebrew fish to /etc/shells
      become: true
      ansible.builtin.lineinfile:
        dest: /etc/shells
        line: "{{ fish_path.stdout }}"
        state: present
      ignore_errors: yes

    - name: "change default shell to fish"
      become: true
      ansible.builtin.user:
        name: '{{ ansible_user }}'
        shell: '{{ fish_path.stdout }}'
        system: true
      ignore_errors: yes

  tags: fish_chsh

- block:
    - name: "create fish config dir"
      ansible.builtin.file:
        path: "{{ xdg_config_home }}/fish"
        state: directory
        mode: '0700'

    - name: "obtain path to fish"
      ansible.builtin.command: which fish
      register: fish_path
      changed_when: false
      check_mode: false

    - name: "create functions dir"
      ansible.builtin.file:
        path: "{{ xdg_config_home }}/fish/functions"
        state: directory
        mode: '0755'

    - name: "install fisher"
      ansible.builtin.get_url:
        url: https://git.io/fisher
        dest: "{{ xdg_config_home }}/fish/functions/fisher.fish"
        mode: '0755'
      register: download_result
      until: download_result is succeeded
      retries: 3
      delay: 5

    - name: "manage fisher plugins file"
      ansible.builtin.copy:
        dest: "{{ xdg_config_home }}/fish/fish_plugins"
        mode: 0600
        content: |
          {% for plugin in (fish.plugins | sort) %}
          {{ plugin }}
          {% endfor %}

    - name: "install plugins with fisher"
      ansible.builtin.shell: "source {{ xdg_config_home }}/fish/functions/fisher.fish; fisher update"
      args:
        executable: '{{ fish_path.stdout }}'
      changed_when: false
      when:
        - fish.plugins is defined
        - fish.plugins | length > 0

    - name: Check if oh-my-fish is installed
      stat:
        path: '{{ ansible_user_dir }}/.local/omf/init.fish'
      register: omf

    - name: Clone oh-my-fish repo
      git:
        repo: 'https://github.com/oh-my-fish/oh-my-fish'
        dest: '/tmp/omf'
        clone: yes
      when: not omf.stat.exists

    - name: Install oh-my-fish
      command: /tmp/omf/bin/install -y --offline --noninteractive --config={{ xdg_config_home }}/fish/omf
      when: not omf.stat.exists

    - name: Check if conf.d/omf.fish exists
      stat:
        path: '{{ xdg_config_home }}/fish/conf.d/omf.fish'
      register: omf_confd

    - name: Copy omf.fish to 00-omf.fish
      ansible.builtin.copy:
        remote_src: true
        src: '{{ xdg_config_home }}/fish/conf.d/omf.fish'
        dest: '{{ xdg_config_home }}/fish/conf.d/00-omf.fish'
      when: omf_confd.stat.exists

    - name: Remove omf.fish
      ansible.builtin.file:
        path: '{{ xdg_config_home }}/fish/conf.d/omf.fish'
        state: absent
      when: omf_confd.stat.exists

    - name: Install omf plugins
      ansible.builtin.shell: "omf install {{ item }}"
      args:
        executable: '{{ fish_path.stdout }}'
      changed_when: false
      with_items: "{{ fish.omf }}"
      when:
        - fish.omf is defined
        - fish.omf | length > 0

  tags: fish_config
