auto_sync = true
ctrl_n_shortcuts = true
filter_mode = "workspace"
search_mode = "fuzzy"
sync_address = "https://atuin.zinn.ca"
update_check = false
workspaces = true
history_filter = [
  "^/opt/homebrew/bin/jj",
  "^cd",
  "^chezmoi",
  "^cm",
  "^gst$",
  "^ll",
  "^ls",
  "^x$",
]

[sync]
records = true
