---
- hosts: localhost
  strategy: linear
  connection: local

  vars:
    os: "{{ (ansible_os_family == 'Darwin') | ternary('darwin', 'linux') }}"
    arch: "{{ (ansible_architecture == 'arm64') | ternary('arm64', 'amd64') }}"

  vars_files:
    - defaults/main.yaml
    - config.yaml

  roles:
    - name: packages
      tags: packages

    - name: fonts
      tags: fonts
      when: ansible_system == "Darwin"

    - name: fish
      tags: fish

    # - name: asdf
    #   tags: asdf
    #   when: ansible_system == "Darwin"

    - name: dotfiles
      tags: dotfiles

    - name: system
      tags: system
