k9s:
  disablePodCounting: false
  imageScans:
    enable: false
    exclusions:
      labels: {}
      namespaces: []
  liveViewAutoRefresh: false
  logger:
    buffer: 5000
    fullScreen: false
    showTime: false
    sinceSeconds: -1
    tail: 100
    textWrap: false
  maxConnRetry: 5
  noExitOnCtrlC: false
  readOnly: false
  refreshRate: 2
  shellPod:
    image: busybox:1.35.0
    limits:
      cpu: 100m
    namespace: default
  skipLatestRevCheck: false
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  ui:
    crumbsless: false
    enableMouse: false
    headless: false
    logoless: false
    noIcons: false
    reactive: false
