[settings]
experimental = true
disable_hints = ["*"]

always_keep_download = false # deleted after install by default
always_keep_install = false  # deleted on failure by default
idiomatic_version_file_enable_tools = ["rust"]

[tools]
